json.id @user.id
json.name @user.name
json.image @user.image.picture(:thumb)
json.role @user.role
json.title @user.title
json.position @user.position
json.email @user.email
json.bizMail @user.bizMail
json.phone @user.phone
json.address @user.address
json.work @user.work
json.education @user.education
json.interests @user.interests
json.full_data @user.full_data
json.languages @user.languages
json.nationality @user.nationality
json.date_of_birth @user.date_of_birth
