default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: rclvapp_development

test:
  <<: *default
  database: rclvapp_test

production:
  <<: *default
  database: rclvapp_production
  username: rclvapp
  password: <%= ENV['RCLVAPP_DATABASE_PASSWORD'] %>
